import type { Metadata } from "next";
import "./globals.css";
import { inter } from "@/ui/fonts";
import QueryProvider from "@/component/QueryProvider";

export const metadata: Metadata = {
  title: "React-Query Study",
  description: "Generated by freeman",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="kr">
      <body className={inter.className}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
